name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9]  # Обновлено до Go 1.19

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Initialize pip
      run: pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build application
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
      run: |
        pyinstaller test.py --onefile

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webview-${{ matrix.os }}
        path: dist/test/*
