name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [1.18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        go get fyne.io/fyne/v2
        go get github.com/webview/webview

    - name: Build application
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          GOOS=windows GOARCH=amd64 go build -o myapp.exe .
        else
          GOOS=linux GOARCH=amd64 go build -o myapp .
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.os }}
        path: myapp*
